#!/bin/bash

# Generate Demo Policies (Without LLM - For Dashboard Testing)
# This creates sample policies so you can see the dashboard in full action

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Generating Demo Policies for Dashboard Testing               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Create NIST policy
cat > output/generated_policies/nist_csf_policy.md << 'POLICY'
# Security Policy - NIST Cybersecurity Framework

**Generated:** $(date)
**Framework:** NIST CSF v1.1
**Application:** sample_app

## Executive Summary

Based on security scan results, this policy addresses 6 identified vulnerabilities:
- 2 HIGH severity issues
- 2 MEDIUM severity issues  
- 2 LOW severity issues

## 1. IDENTIFY (ID)

### ID.RA-5: Threats and Vulnerabilities

**Finding:** SQL Injection vulnerability in database queries
- **Location:** sample_app/app.py:28
- **CWE:** CWE-89
- **Severity:** MEDIUM

**Policy Requirement:**
- All database queries MUST use parameterized statements
- Input validation required for all user-supplied data
- Regular code reviews focusing on injection vulnerabilities

### ID.RA-5: Command Injection Risk

**Finding:** Shell command execution with user input
- **Location:** sample_app/app.py:38
- **CWE:** CWE-78
- **Severity:** HIGH

**Policy Requirement:**
- Prohibit shell=True in subprocess calls
- Implement input sanitization
- Use subprocess argument lists instead of shell strings

## 2. PROTECT (PR)

### PR.AC-1: Access Control

**Finding:** Hardcoded credentials detected
- **Location:** sample_app/app.py:14
- **CWE:** CWE-259
- **Severity:** LOW

**Policy Requirement:**
- Store credentials in environment variables or secure vaults
- Implement secrets management system
- Rotate credentials quarterly

### PR.DS-5: Protection Against Data Leaks

**Finding:** Debug mode enabled in production
- **Location:** sample_app/app.py:58
- **CWE:** CWE-94
- **Severity:** HIGH

**Policy Requirement:**
- Debug mode MUST be disabled in production
- Implement proper logging without exposing sensitive data
- Use environment-based configuration

## 3. DETECT (DE)

### DE.CM-1: Network Monitoring

**Policy Requirement:**
- Monitor for SQL injection attempts
- Implement intrusion detection for command injection
- Log all security-relevant events

## 4. RESPOND (RS)

### RS.AN-1: Incident Analysis

**Policy Requirement:**
- Immediate patching required for HIGH severity issues
- Medium issues must be addressed within 30 days
- Maintain incident response plan

## 5. RECOVER (RC)

### RC.RP-1: Recovery Planning

**Policy Requirement:**
- Regular security assessments
- Automated vulnerability scanning in CI/CD
- Security training for development team

## Compliance Metrics

- **Total Vulnerabilities:** 6
- **Critical Issues:** 0
- **High Priority:** 2 (Requires immediate action)
- **Risk Score:** 6.5/10

## Remediation Timeline

| Priority | Count | Deadline |
|----------|-------|----------|
| HIGH     | 2     | 7 days   |
| MEDIUM   | 2     | 30 days  |
| LOW      | 2     | 90 days  |

---
*Policy generated by DevSecOps AI - NIST CSF Framework*
POLICY

# Create ISO 27001 policy
cat > output/generated_policies/iso_27001_policy.md << 'POLICY'
# Information Security Policy - ISO/IEC 27001:2022

**Generated:** $(date)
**Standard:** ISO/IEC 27001:2022
**Application:** sample_app
**Classification:** Internal Use

## 1. Introduction

This policy addresses security vulnerabilities identified through automated scanning aligned with ISO/IEC 27001:2022 controls.

## 2. Scope

Applies to all application code, dependencies, and deployment environments.

## 3. Security Controls

### A.8.1 - User Endpoint Devices

**Control:** Protection against malware and unauthorized access

**Implementation:**
- Address hardcoded credentials (CWE-259)
- Implement secure credential management
- Use hardware security modules where applicable

### A.8.2 - Privileged Access Rights

**Control:** Allocation and management of privileged access rights

**Findings:**
- Shell command injection risk (HIGH - CWE-78)
- Requires privilege escalation prevention

**Required Actions:**
1. Remove shell=True from subprocess calls
2. Implement least privilege principle
3. Audit privileged operations

### A.8.3 - Information Access Restriction

**Control:** Access to information and other associated assets restricted

**Findings:**
- SQL injection vulnerability (MEDIUM - CWE-89)
- Potential unauthorized data access

**Required Actions:**
1. Use parameterized queries exclusively
2. Implement input validation framework
3. Apply principle of least privilege to database access

### A.8.4 - Access to Source Code

**Control:** Read and write access to source code restricted

**Findings:**
- Debug mode enabled (HIGH - CWE-94)
- Exposes source code and system information

**Required Actions:**
1. Disable debug mode in production
2. Implement proper error handling
3. Configure environment-specific settings

## 4. Risk Assessment

### Risk Level: MEDIUM-HIGH

**Justification:**
- 2 HIGH severity vulnerabilities
- Potential for data breach
- Command execution risks

### Treatment Plan:
1. **HIGH Priority** (7 days): Shell injection, Debug mode
2. **MEDIUM Priority** (30 days): SQL injection, Network exposure
3. **LOW Priority** (90 days): Hardcoded secrets, Import security

## 5. Compliance Requirements

All development teams must:
- Conduct security code reviews
- Implement automated security scanning
- Follow secure coding guidelines
- Document security exceptions

## 6. Monitoring and Review

- **Frequency:** Quarterly security assessments
- **Responsibility:** Security team
- **Metrics:** Vulnerability count, remediation time
- **Reporting:** Monthly security dashboard

## 7. Policy Enforcement

Non-compliance may result in:
- Build failures in CI/CD pipeline
- Code deployment blocks
- Security team escalation

---
*ISO/IEC 27001:2022 Compliance Policy*
*Generated by DevSecOps AI Platform*
POLICY

# Create CIS Controls policy
cat > output/generated_policies/cis_controls_v8_policy.md << 'POLICY'
# Security Policy - CIS Controls v8

**Generated:** $(date)
**Framework:** CIS Controls v8
**Application:** sample_app
**Asset Type:** Web Application

## Implementation Groups

This policy addresses vulnerabilities across CIS IG1, IG2, and IG3.

## Control 1: Inventory and Control of Enterprise Assets

**Status:** PASS
- Application identified: sample_app
- Language: Python
- Dependencies: Flask framework

## Control 2: Inventory and Control of Software Assets

**Finding:** Insecure subprocess module usage
- **CWE:** CWE-78
- **Severity:** LOW
- **Control:** 2.5 - Allowlist Authorized Software

**Action Required:**
- Review and document all subprocess calls
- Implement allowlist of permitted commands
- Regular software inventory audits

## Control 3: Data Protection

**Finding:** SQL Injection vulnerability
- **CWE:** CWE-89
- **Severity:** MEDIUM
- **Control:** 3.11 - Encrypt Sensitive Data at Rest

**Action Required:**
- Implement parameterized queries
- Enable SQL query logging
- Encrypt database connections

**Finding:** Hardcoded credentials
- **CWE:** CWE-259
- **Severity:** LOW
- **Control:** 3.10 - Encrypt Sensitive Data in Transit

**Action Required:**
- Use environment variables
- Implement secrets management
- Regular credential rotation

## Control 4: Secure Configuration

**Finding:** Debug mode enabled
- **CWE:** CWE-94
- **Severity:** HIGH
- **Control:** 4.1 - Establish Secure Configurations

**Action Required:**
- Create production configuration template
- Disable debug in production deployments
- Implement configuration validation

**Finding:** Network exposure
- **CWE:** CWE-605
- **Severity:** MEDIUM
- **Control:** 4.4 - Implement and Manage Firewall

**Action Required:**
- Bind to specific interfaces only
- Implement network segmentation
- Configure firewall rules

## Control 16: Application Software Security

**Finding:** Command injection via shell
- **CWE:** CWE-78
- **Severity:** HIGH
- **Control:** 16.1 - Establish Secure Coding Practices

**Action Required:**
- Never use shell=True with user input
- Implement input validation
- Security code review process

**Overall Assessment:**
- **Total Findings:** 6
- **Critical Controls Affected:** 4
- **Implementation Group:** IG2 (Intermediate)

## Remediation Priority Matrix

| CIS Control | Finding | Priority | Timeline |
|-------------|---------|----------|----------|
| 16.1 | Command Injection | CRITICAL | 7 days |
| 4.1 | Debug Mode | CRITICAL | 7 days |
| 3.11 | SQL Injection | HIGH | 14 days |
| 4.4 | Network Exposure | MEDIUM | 30 days |
| 3.10 | Hardcoded Creds | LOW | 60 days |
| 2.5 | Subprocess Import | LOW | 90 days |

## Continuous Monitoring

- Automated scans in CI/CD pipeline
- Weekly vulnerability assessments
- Monthly compliance reporting
- Quarterly security reviews

---
*CIS Controls v8 Implementation Policy*
*Generated by DevSecOps AI*
POLICY

echo "✅ Created 3 demo policies:"
echo "   - output/generated_policies/nist_csf_policy.md"
echo "   - output/generated_policies/iso_27001_policy.md"
echo "   - output/generated_policies/cis_controls_v8_policy.md"
echo ""

# Create sample evaluation results
cat > output/evaluation_results/evaluation_$(date +%Y%m%d_%H%M%S).json << 'EVAL'
{
  "timestamp": "$(date -Iseconds)",
  "framework": "NIST_CSF",
  "policy_file": "nist_csf_policy.md",
  "metrics": {
    "bleu_score": 72.5,
    "rouge_l_score": 68.3,
    "compliance_score": 85.0,
    "readability_score": 78.2
  },
  "analysis": {
    "strengths": [
      "Clear structure aligned with NIST framework",
      "Comprehensive coverage of identified vulnerabilities",
      "Actionable remediation guidance"
    ],
    "areas_for_improvement": [
      "Add more specific technical implementation details",
      "Include cost estimates for remediation",
      "Expand monitoring and detection procedures"
    ]
  },
  "compliance_check": {
    "required_sections": [
      "IDENTIFY",
      "PROTECT", 
      "DETECT",
      "RESPOND",
      "RECOVER"
    ],
    "present_sections": [
      "IDENTIFY",
      "PROTECT",
      "DETECT", 
      "RESPOND",
      "RECOVER"
    ],
    "completeness": 100
  }
}
EVAL

echo "✅ Created evaluation results"
echo ""
echo "🔄 Refresh your dashboard now!"
echo "   The 📄 Generated Policies and 📈 Quality Metrics should appear"
echo ""
echo "Dashboard: http://localhost:5000"
echo ""
