# GitHub Actions Workflow for DevSecOps AI
name: DevSecOps AI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for SonarQube
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        pytest tests/unit --cov=. --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
    
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: htmlcov/

  # SonarQube removed - using Bandit for SAST

  sast-bandit:
    name: SAST - Bandit Security Scanner
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Bandit
      run: pip install bandit[toml]
    
    - name: Run Bandit scan
      run: |
        mkdir -p data/reports
        bandit -r . -f json -o data/reports/bandit_report.json || true
        bandit -r . -f html -o data/reports/bandit_report.html || true
    
    - name: Upload Bandit results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-reports
        path: data/reports/bandit_report.*

  sca-dependency-check:
    name: SCA - OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'DevSecOps AI'
        path: '.'
        format: 'ALL'
        out: 'data/reports'
    
    - name: Upload Dependency-Check results
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-reports
        path: data/reports/dependency-check-report.*

  sca-safety:
    name: SCA - Safety Check (Python)
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Safety
      run: pip install safety
    
    - name: Run Safety check
      run: |
        mkdir -p data/reports
        safety check --json --output data/reports/safety_report.json || true
    
    - name: Upload Safety results
      uses: actions/upload-artifact@v3
      with:
        name: safety-reports
        path: data/reports/safety_report.json

  dast-zap:
    name: DAST - OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: ${{ secrets.TARGET_URL }}
        rules_file_name: 'pipelines/zap_rules.tsv'
        cmd_options: '-a -j'
    
    - name: Upload ZAP results
      uses: actions/upload-artifact@v3
      with:
        name: zap-reports
        path: |
          report_html.html
          report_json.json

  policy-generation:
    name: Generate Security Policies
    runs-on: ubuntu-latest
    needs: [sast-bandit, sca-dependency-check, sca-safety]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Download scan results
      uses: actions/download-artifact@v3
      with:
        path: data/reports/
    
    - name: Generate NIST CSF policies
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
      run: |
        python main.py generate \
          --input data/reports/ \
          --output output/generated_policies/ \
          --framework NIST_CSF
    
    - name: Generate ISO 27001 policies
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
      run: |
        python main.py generate \
          --input data/reports/ \
          --output output/generated_policies/ \
          --framework ISO_27001
    
    - name: Upload generated policies
      uses: actions/upload-artifact@v3
      with:
        name: generated-policies
        path: output/generated_policies/

  evaluation:
    name: Evaluate Generated Policies
    runs-on: ubuntu-latest
    needs: policy-generation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Download generated policies
      uses: actions/download-artifact@v3
      with:
        name: generated-policies
        path: output/generated_policies/
    
    - name: Run evaluation
      run: |
        python main.py evaluate \
          --policies output/generated_policies/ \
          --reference data/reference_policies/ \
          --output output/evaluation_results/
    
    - name: Display evaluation summary
      run: cat output/evaluation_results/summary.json
    
    - name: Upload evaluation results
      uses: actions/upload-artifact@v3
      with:
        name: evaluation-results
        path: output/evaluation_results/

  generate-report:
    name: Generate Final Report
    runs-on: ubuntu-latest
    needs: evaluation
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Download evaluation results
      uses: actions/download-artifact@v3
      with:
        name: evaluation-results
        path: output/evaluation_results/
    
    - name: Download generated policies
      uses: actions/download-artifact@v3
      with:
        name: generated-policies
        path: output/generated_policies/
    
    - name: Generate final report
      run: |
        python scripts/generate_final_report.py \
          --evaluation output/evaluation_results/ \
          --policies output/generated_policies/ \
          --output reports/final_report.pdf
    
    - name: Upload final report
      uses: actions/upload-artifact@v3
      with:
        name: final-report
        path: reports/final_report.pdf
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: reports/final_report.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
